# -*- coding: utf-8 -*-
"""ropt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6Z16UU0rs1p3OfhMKKeYWRzfJvHY3-z
"""

import streamlit as st
import pandas as pd
import pulp
from datetime import datetime

st.set_page_config(page_title="Pedido Óptimo + Financiamiento", layout="wide")

st.title("📦 Mariquería Ramírez - Pedido Óptimo con Financiamiento")

# -------------------------
# Datos
# -------------------------
data = [
["MARISCOS","Camarón Seco","250 Gramos",0,1,1,70],
["SAMS","CLORO","10 LITROS",0,1,1,119],
["SAMS","FABULOSO (LAVANDA)","10 LITROS",0,1,1,179],
["SAMS","ACEITE 1-2-3","PAQUETE 3 LITROS",0,1,24,127],
["SAMS","VALENTINA ROJA","350 ML (6 PZAS)",0,6,6,91],
["MATERIA PRIMA","CHAROLA 835","FILETES",0,1,1,35],
["MATERIA PRIMA","CHAROLA 855","PEDIDOS GRANDES",0,1,1,35],
["MATERIA PRIMA","CHAROLA 066","PEDIDOS MEDIANOS",0,1,1,35],
["MATERIA PRIMA","BOLSA CHICA (1)","PEDIDOS CHICOS",0,1,1,40],
["MATERIA PRIMA","BOLSA (3)","PEDIDOS GRANDES",0,1,1,40],
["MATERIA PRIMA","TAZÓN (MEDIO LITRO)","PAQUETE",0,1,1,35],
["MATERIA PRIMA","TAZÓN (LITRO)","PAQUETE",0,1,1,35],
["MATERIA PRIMA","TAPA TAZÓN","PAQUETE",0,1,1,50],
["MATERIA PRIMA","ROLLO BOLSA POLIPAPEL","PAQUETE",0,1,1,80],
["MATERIA PRIMA","ROYAL","1 KILO",0,1,1,40],
["SALSAS","VALENTINA NEGRA","350 ML",0,1,2,20],
["SALSAS","VALENTINA AZUL","350 ML",0,1,2,25],
["SALSAS","LA GLORIA (ROJA)","250 ML",0,1,2,40],
["SALSAS","LA GLORIA (AMARILLA)","250 ML",0,1,5,40],
["SALSAS","LOP JU (ROJA)","250 ML",0,1,2,40],
["SALSAS","LOP JU (AMARILLA)","250 ML",0,1,5,40],
["SALSAS","LOS JAROCHOS (AMARILLA)","150 ML",0,1,5,40],
["SALSAS","SALSA INGLESA","250 ML",0,1,1,70],
["SALSAS","SALSA BRUJA","40 ML",0,1,1,30],
["SALSAS","ACEITE DE OLIVO","350 ML",0,1,1,105],
["SALSAS","VALENTINA BOLSITA","1 KG",0,1,2,50],
["SALSAS","SALADITAS","1 PAQUETE",0,1,2,60],
["SAN JUAN","SAL DE AJO","1 KG",0,1,1,50],
["SAN JUAN","CHILE PUYA","GRAMAJE",0,1,1,20],
["SAN JUAN","CHILE GUAJIYO","GRAMAJE",0,1,1,20],
["3B","HARINA 3 SOLES","1 KILO",0,1,12,16],
["3B","MAYONESA","CHICA",0,1,3,30],
["3B","MAYONESA","MEDIANA",0,1,3,49],
["3B","SERVILLETA_SERVICIO","PAQUETE",0,1,2,42],
["3B","CATSUP","1 LITRO",0,1,3,30],
["3B","GEL ANTIBACTERIAL","200 ML",0,1,1,20],
["3B","ARROZ VALLE VERDE","1 KILO",0,1,7,17],
]

columns = ["Familia","Producto","Especificación","Inventario","CMVP","Consumo mensual","Costo unitario"]
df = pd.DataFrame(data, columns=columns)

# -------------------------
# Entrada usuario
# -------------------------
st.subheader("✏️ Captura inventario actual")
edited_df = st.data_editor(df)

caja = st.number_input("💰 Caja disponible", min_value=0.0, value=1000.0)

# -------------------------
# Optimización
# -------------------------
if st.button("🚀 Calcular pedido óptimo"):

    model = pulp.LpProblem("Pedido_Optimo_Financiamiento", pulp.LpMinimize)

    # Variables
    k = {i: pulp.LpVariable(f"k_{i}", lowBound=0, cat="Integer") for i in edited_df.index}
    financiamiento = pulp.LpVariable("Financiamiento", lowBound=0)

    # Objetivo
    model += financiamiento

    # Restricciones de demanda
    for i in edited_df.index:
        demanda = edited_df.loc[i, "Consumo mensual"]
        inventario = edited_df.loc[i, "Inventario"]
        cmvp = edited_df.loc[i, "CMVP"]

        necesidad = max(0, demanda - inventario)
        model += cmvp * k[i] >= necesidad

    # Restricción financiera
    costo_total = pulp.lpSum(
        edited_df.loc[i, "Costo unitario"] *
        edited_df.loc[i, "CMVP"] *
        k[i]
        for i in edited_df.index
    )

    model += costo_total <= caja + financiamiento

    # Resolver
    model.solve()

    # -------------------------
    # Resultados
    # -------------------------
    result = edited_df.copy()

    result["Lotes"] = [pulp.value(k[i]) for i in edited_df.index]
    result["Pedido óptimo"] = result["Lotes"] * result["CMVP"]
    result["Costo pedido"] = result["Pedido óptimo"] * result["Costo unitario"]

    st.subheader("📊 Resultado")
    st.dataframe(result)

    st.subheader("💰 Resumen financiero")
    st.metric("Financiamiento necesario", f"${pulp.value(financiamiento):,.2f}")
    st.metric("Costo total", f"${result['Costo pedido'].sum():,.2f}")

    # -------------------------
    # Descargar CSV único
    # -------------------------
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")

    csv_unificado = result.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="📥 Descargar CSV completo",
        data=csv_unificado,
        file_name=f"pedido_optimo_{timestamp}.csv",
        mime="text/csv"
    )